peg.factors = {
	kiersey: {
		extravert: {
			test: 'kiersey',
			factor: 'extravert',
			left: 'Extravert',
			right: 'Introvert',
		},
		sensible: {
			test: 'kiersey',
			factor: 'sensible',
			left: 'Sensible-Practical',
			right: 'Intuitive-Creative',
		},
		thinking: {
			test: 'kiersey',
			factor: 'thinking',
			left: 'Thinking',
			right: 'Feeling',
		},
		judicious: {
			test: 'kiersey',
			factor: 'judicious',
			left: 'Judicious',
			right: 'Perceptive-Spontaneous',
		},
	},
	pp: {
		definitions: {
			test: 'pp',
			factor: 'definitions',
			left: 'Need for Definitions',
		},
		feelings: {
			test: 'pp',
			factor: 'feelings',
			left: 'Emphasis on Personal Feelings',
		},
		efficiency: {
			test: 'pp',
			factor: 'efficiency',
			left: 'Emphasis on Efficiency',
		},
		curiosity: {
			test: 'pp',
			factor: 'curiosity',
			left: 'Active Curiosity',
		},
		authority: {
			test: 'pp',
			factor: 'authority',
			left: 'Need for Established Authority',
		},
		resistance: {
			test: 'pp',
			factor: 'resistance',
			left: 'Resistance to Social Pressure',
		},
		wariness: {
			test: 'pp',
			factor: 'wariness',
			left: 'Wariness of People',
		},
		tools: {
			test: 'pp',
			factor: 'tools',
			left: 'Pleasure in Tool Skills',
		},
		affection: {
			test: 'pp',
			factor: 'affection',
			left: 'Need for Affectional Acceptance',
		},
		acclaim: {
			test: 'pp',
			factor: 'acclaim',
			left: 'Need for Public Acclaim',
		},
		pressure: {
			test: 'pp',
			factor: 'pressure',
			left: 'Feelings of Pressure',
		},
		direct: {
			test: 'pp',
			factor: 'direct',
			left: 'Desire to Direct Activities',
		},
		avoidance: {
			test: 'pp',
			factor: 'avoidance',
			left: 'Avoidance of Confrontations',
		},
		disappointment: {
			test: 'pp',
			factor: 'disappointment',
			left: 'Feelings of Disappointment',
		},
	},
	zinn: {
		adventure: {
			test: 'zinn',
			factor: 'adventure',
			left: 'Adventure-Freedom',
			right: 'Comfort-Control',
		},
		personal: {
			test: 'zinn',
			factor: 'personal',
			left: 'Personal Affiliation',
			right: 'Public Recognition',
		},
	},
	pf16global: {
		extraversion: {
			test: 'pf16global',
			factor: 'extraversion',
			left:  'Introversion',
			right: 'Extraversion',
		},
		anxiety: {
			test: 'pf16global',
			factor: 'anxiety',
			left: 'Low Anxiety',
			right: 'Anxiety',
		},
		tough: {
			test: 'pf16global',
			factor: 'tough',
			left: 'Receptivity',
			right: 'Tough-Mindedness',
		},
		independence: {
			test: 'pf16global',
			factor: 'independence',
			left: 'Accomodation',
			right:'Independence',
		},
		selfcontrol: {
			test: 'pf16global',
			factor: 'selfcontrol',
			left: 'Unrestrained',
			right: 'Self-Control',
		},
	},
	pf16primary: {
		warm: {
			test: 'pf16primary',
			factor: 'warm',
			code: 'a',
			left: 'Reserved',
			leftsub: 'aloof, detached',
			right: 'Warm',
			rightsub: 'friendly, attentive to others',
		},
		abstract: {
			test: 'pf16primary',
			factor: 'abstract',
			code: 'b',
			left: 'Concrete',
			leftsub: 'less reasoning ability',
			right: 'Abstract',
			rightsub: 'more reasoning ability',
		},
		stable: {
			test: 'pf16primary',
			factor: 'stable',
			code: 'c',
			left: 'Reactive',
			leftsub: 'less ego strength',
			right: 'Emotionally Stable',
			rightsub: 'more ego strength',
		},
		dominant: {
			test: 'pf16primary',
			factor: 'dominant',
			code: 'e',
			left: 'Deferential',
			leftsub: 'submissive, humble',
			right: 'Dominant',
			rightsub: 'assertive, competitive',
		},
		lively: {
			test: 'pf16primary',
			factor: 'lively',
			code: 'f',
			left: 'Serious',
			leftsub: 'inhibited, somber',
			right: 'Lively',
			rightsub: 'energetic, carefree',
		},
		rule: {
			test: 'pf16primary',
			factor: 'rule',
			code: 'g',
			left: 'Expedient',
			leftsub: 'unconventional',
			right: 'Ruleconscious',
			rightsub: 'conventional',
		},
		bold: {
			test: 'pf16primary',
			factor: 'bold',
			code: 'h',
			left: 'Shy',
			leftsub: 'socially timid',
			right: 'Socially Bold',
			rightsub: 'venturesome, seeks attention',
		},
		sensitive: {
			test: 'pf16primary',
			factor: 'sensitive',
			code: 'i',
			left: 'Utilitarian',
			leftsub: 'tough, unsentimental',
			right: 'Sensitive',
			rightsub: 'refined, sentimental',
		},
		vigilant: {
			test: 'pf16primary',
			factor: 'vigilant',
			code: 'i',
			left: 'Trusting',
			leftsub: 'accepting, easygoing',
			right: 'Vigilant',
			rightsub: 'suspicious, skeptical',
		},
		abstracted: {
			test: 'pf16primary',
			factor: 'abstracted',
			code: 'm',
			left: 'Grounded',
			leftsub: 'practical, pragmatic',
			right: 'Abstracted',
			rightsub: 'idea-oriented, imaginative',
		},
		private: {
			test: 'pf16primary',
			factor: 'private',
			code: 'n',
			left: 'Forthright',
			leftsub: 'naive, self-disclosing',
			right: 'Private',
			rightsub: 'discreet, shrewd',
		},
		apprehensive: {
			test: 'pf16primary',
			factor: 'apprehensive',
			code: 'o',
			left: 'Self-Assured',
			leftsub: 'secure, untroubled',
			right: 'Apprehensive',
			rightsub: 'guiltprone, worrying',
		},
		open: {
			test: 'pf16primary',
			factor: 'open',
			code: 'q1',
			left: 'Traditional',
			leftsub: 'resists change',
			right: 'Open-to-change',
			rightsub: 'experimenting',
		},
		selfreliant: {
			test: 'pf16primary',
			factor: 'selfreliant',
			code: 'q2',
			left: 'Group-Oriented',
			leftsub: 'socially group-dependent',
			right: 'Self-Reliant',
			rightsub: 'solitary, individualistic',
		},
		perfectionist: {
			test: 'pf16primary',
			factor: 'perfectionist',
			code: 'q3',
			left: 'Tolerates Disorder',
			leftsub: 'careless',
			right: 'Perfectionistic',
			rightsub: 'orderly, compulsive',
		},
		tense: {
			test: 'pf16primary',
			factor: 'tense',
			code: 'q4',
			left: 'Relaxed',
			leftsub: 'placid, patient',
			right: 'Tense',
			rightsub: 'driven, fastpaced',
		},
	},
	eji: {
		aware: {
			test: 'eji',
			factor: 'aware',
			code: 'aw',
			left: 'Being Aware of Emotions',
		},
		identifyown: {
			test: 'eji',
			factor: 'identifyown',
			code: 'is',
			left: 'Identifying Own Emotions',
		},
		identifyothers: {
			test: 'eji',
			factor: 'identifyothers',
			code: 'io',
			left: 'Identifying Others\' Emotions',
		},
		manageown: {
			test: 'eji',
			factor: 'manageown',
			code: 'ms',
			left: 'Managing Own Emotions',
		},
		manageothers: {
			test: 'eji',
			factor: 'manageothers',
			code: 'mo',
			left: 'Managing Others\' Emotions',
		},
		problemsolving: {
			test: 'eji',
			factor: 'problemsolving',
			code: 'ps',
			left: 'Using Emotions in Problem Solving',
		},
		express: {
			test: 'eji',
			factor: 'express',
			code: 'ex',
			left: 'Expressing Emotions Adaptively',
		},
		impression: {
			test: 'eji',
			factor: 'impression',
			code: 'im',
			left: 'Impression Management',
		},
	},
}
