peg.nourishments = [
	{ test:'kiersey',     factor:'extravert',      range:'high',      narrative:'Being with large groups of people.' },
	{ test:'kiersey',     factor:'extravert',      range:'low',       narrative:'Being alone.  Being in one-on-one or small group conversations that are deeper in meaning and content.  This "essence" communication will nourish me, along with my time alone, and charge my psychic or life batteries.' },
	{ test:'kiersey',     factor:'extravert',      range:'balanced',  narrative:'I am nourished by two different sources.  On an Introvert level, I am nourished by being alone or in one-on-one or small group conversations.  On the Extravert level, I am nourished by being with large groups of people, many of whom I may not know, and with a very different depth of communication.  This communication has less substance and is not as deep as one-on-one communication.' },
	{ test:'kiersey',     factor:'judicious',      range:'low',       narrative:'I enjoy planning, linear timetables, and doing one project at a time in step-by-step, concrete/sequential manner.' },
	{ test:'kiersey',     factor:'judicious',      range:'low',       narrative:'I value my freedom and will explore roads less traveled.' },
	{ test:'kiersey',     factor:'judicious',      range:'low',       narrative:'I do much better with a project table as opposed to a desk.' },
	{ test:'pp',          factor:'definitions',    range:'average',   narrative:'I need a combination of knowing what is expected of me and the ability to use my creativity.' },
	{ test:'pp',          factor:'curiosity',      range:'high',      narrative:'I am energized by learning new things accumulating information and wisdom.' },
	{ test:'pp',          factor:'curiosity',      range:'high',      narrative:'I am energized by learning new things accumulating information and wisdom.' },
	{ test:'pp',          factor:'acclaim',        range:'high',      narrative:'I am motivated by being praised publicly for doing a good job, by the team that I work with and the people who are over me.' },
],

peg.burnouts = [
	{ test:'kiersey',     factor:'extravert',      range:'low',       narrative:'Many times, I may find that I am used up in my interaction with people at work.  I may need to go home and retreat to being alone or with small groups in one-on-one "essence" communication.' },
	{ test:'kiersey',     factor:'extravert',      range:'high',      narrative:'I may get lonely if I spend too much time alone.' },
	{ test:'kiersey',     factor:'extravert',      range:'balanced',  narrative:'On an Introvert level, I may find that I am used up in my interaction with large groups of people.  On the Extravert level, I may get lonely if I spend too much time alone.' },
	{ test:'kiersey',     factor:'judicious',      range:'high',      narrative:'Too many simultaneous projects.' },
	{ test:'kiersey',     factor:'judicious',      range:'low',       narrative:'If someone changes or consolidates the piles that separate each project.' },
	{ test:'pp',          factor:'curiosity',      range:'high',      narrative:'Repetitive routine.' },
	{ test:'pp',          factor:'resistance',     range:'high',      narrative:'In the event I get too far out of the context of social norms, a percentage of the population may turn on me.' },
	{ test:'pp',          factor:'definitions',    range:'low',       narrative:'Micro-management.' },
	{ test:'pp',          factor:'wariness',       range:'low',       narrative:'I am highly trusting of people, and tend to want to see their potential goodness. But some people do not wish to act on their own potential or goodness, which may disappoint me, mystify me, or allow others to take advantage of me.' },
],

peg.gifts = [
	{ test:'kiersey',     factor:'extravert',      range:'high',      narrative:'An ability to interact with large groups of people, even if I don\'t know many of them.' },
	{ test:'kiersey',     factor:'extravert',      range:'low',       narrative:'An ability to work in solitary conditions.' },
	{ test:'kiersey',     factor:'extravert',      range:'balanced',  narrative:'' },
	{ test:'kiersey',     factor:'sensible',       range:'high',      narrative:'Practicality.' },
	{ test:'kiersey',     factor:'sensible',       range:'low',       narrative:'Creativity.' },
	{ test:'kiersey',     factor:'sensible',       range:'balanced',  narrative:'I have an unusual understanding of both Sensible/Practical people and Intuitive/Creative people (the ability to think both ways and speak both languages).' },
	{ test:'kiersey',     factor:'thinking',       range:'high',      narrative:'I have the gift of trying to make things rational and, therefore, understandable.' },
	{ test:'kiersey',     factor:'thinking',       range:'low',       narrative:'As a high feeler, I may be empathic.' },
	{ test:'kiersey',     factor:'thinking',       range:'low',       narrative:'I can use my personal feelings as inspiration for my endeavors.' },
	{ test:'kiersey',     factor:'thinking',       range:'balanced',  narrative:'I am open to the process of learning to balance feelings and rational thought temperament.' },
	{ test:'kiersey',     factor:'judicious',      range:'high',      narrative:'I enjoy planning, linear timetables, and doing one project at a time in step-by-step, concrete/sequential manner.' },
	{ test:'kiersey',     factor:'judicious',      range:'high',      narrative:'The ability to make contingency plans for just about everything.' },
	{ test:'kiersey',     factor:'judicious',      range:'high',      narrative:'The ability to compile information and research.' },
	{ test:'kiersey',     factor:'judicious',      range:'low',      narrative:'Able to handle several projects at one time.' },  
	{ test:'kiersey',     factor:'judicious',      range:'low',      narrative:'Good at keeping the big picture in my head and seeing how all the pieces interact' },
	{ test:'kiersey',     factor:'judicious',      range:'low',      narrative:'Gathering information until the last minute, seeing the big picture, and coming up with unique solutions or conclusions to connect new information to what I already know.' },
	{ test:'kiersey',     factor:'judidious',      range:'balanced',  narrative:'I tend to appreciate the big picture, and I also can attention to details.' },

	{ test:'pp',          factor:'definitions',    range:'high',      narrative:'' },
	{ test:'pp',          factor:'definitions',    range:'low',       narrative:'I am a high self-starter and can plan and implement complete projects by myself.' },
	{ test:'pp',          factor:'definitions',    range:'average',   narrative:'I have the gift of being able to do a project, given I know at least half of what is expected of me.' },
	{ test:'pp',          factor:'efficiency',     range:'high',      narrative:'The knack for preparation and cleanup as well as keeping track of details.' },
	{ test:'pp',          factor:'efficiency',     range:'low',       narrative:'' },
	{ test:'pp',          factor:'efficiency',     range:'average',   narrative:'' },
	{ test:'pp',          factor:'curiosity',      range:'high',      narrative:'I am open to new information.' },
	{ test:'pp',          factor:'curiosity',      range:'low',       narrative:'' },
	{ test:'pp',          factor:'curiosity',      range:'average',   narrative:'' },
	{ test:'pp',          factor:'authority',      range:'high',      narrative:'This indicates that I have a very high preference to learn from someone who is an expert in his or her field.' },
	{ test:'pp',          factor:'authority',      range:'low',       narrative:'I can learn from just about anyone as long as they make sense.' },
	{ test:'pp',          factor:'authority',      range:'average',   narrative:'' },
	{ test:'pp',          factor:'resistance',     range:'high',      narrative:'This indicates that I may resist society\'s rules about what I should do with my life. It may also indicate a highly developed inner rebel.' },
	{ test:'pp',          factor:'resistance',     range:'low',       narrative:'I appear not to be affected by other people\'s opinions, however, I appear to want to please them as opposed to rocking the boat.  In other words, I have learned to tell people what they want to hear and then do my own thing.' },
	{ test:'pp',          factor:'resistance',     range:'average',   narrative:'' },
	{ test:'pp',          factor:'wariness',       range:'high',      narrative:'I can set and maintain good boundaries to keep me safe.' },
	{ test:'pp',          factor:'wariness',       range:'high',      narrative:'I will unlikely to be taken advantage of or conned.' },
	{ test:'pp',          factor:'wariness',       range:'low',       narrative:'' },
	{ test:'pp',          factor:'wariness',       range:'average',   narrative:'' },
	{ test:'pp',          factor:'tools',          range:'high',      narrative:'This very high bar in tool skills indicates how much I enjoy working with my hands.' },
	{ test:'pp',          factor:'tools',          range:'low',       narrative:'This indicates that I prefer to work with my mind rather than my hands.' }, 
	{ test:'pp',          factor:'tools',          range:'average',   narrative:'' }, 
	{ test:'pp',          factor:'affection',      range:'high',      narrative:'This tells us that affection and acceptance are more of a need for me than for most people.' },
	{ test:'pp',          factor:'affection',      range:'low',       narrative:'I am not emotionally needy.' },
	{ test:'pp',          factor:'affection',      range:'average',   narrative:'' },
	{ test:'pp',          factor:'acclaim',        range:'high',      narrative:'This bar indicates it is very important in my career as well as my personal life to be praised for my accomplishments publicly.  This can be in the form of awards and certificates of appreciation, as well as being told that I am doing a good job in front of others.' },
	{ test:'pp',          factor:'acclaim',        range:'low',       narrative:'I do not need a lot of public acclaim for doing a good job.  I have my own internal standards.' },
	{ test:'pp',          factor:'acclaim',        range:'average',   narrative:'' },
	{ test:'pp',          factor:'pressure',       range:'high',      narrative:'This indicates that at this time I am feeling very pressured to do more than I can. This also indicates a high inner pusher or driver part of me that pushes me beyond what my body and mind can do.' }, 
	{ test:'pp',          factor:'pressure',       range:'low',       narrative:'' },
	{ test:'pp',          factor:'pressure',       range:'average',   narrative:'' },
	{ test:'pp',          factor:'direct',         range:'high',      narrative:'' },
	{ test:'pp',          factor:'direct',         range:'low',       narrative:'I have the ability of being able to share control as opposed to directing activities all the time.  I can take charge when I need to, though my pattern is to wait for others to fail and then fix it for them.' },
	{ test:'pp',          factor:'direct',         range:'average',   narrative:'' },
	{ test:'pp',          factor:'avoidance',      range:'high',      narrative:'' },
	{ test:'pp',          factor:'avoidance',      range:'low',       narrative:'I have the capacity to tell it like it is and to let people know where they stand with me at all times, if I choose.' },
	{ test:'pp',          factor:'avoidance',      range:'low',       narrative:'I have the Ability to confront people and have difficult conversations.' },
	{ test:'pp',          factor:'avoidance',      range:'average',   narrative:'' },
	{ test:'pp',          factor:'disappointment', range:'high',      narrative:'' },
	{ test:'pp',          factor:'disappointment', range:'low',       narrative:'I do not blame others when things go wrong.' },
	{ test:'pp',          factor:'disappointment', range:'average',   narrative:'' },

	{ test:'zinn',        factor:'adventure',      range:'high',      narrative:'I can deal with life\'s unpredictability well, and frame it as an adventure.' },
	{ test:'zinn',        factor:'adventure',      range:'low',       narrative:'' },
	{ test:'zinn',        factor:'adventure',      range:'balanced',  narrative:'' },
	{ test:'zinn',        factor:'personal',       range:'high',      narrative:'' },
	{ test:'zinn',        factor:'personal',       range:'low',       narrative:'' },
	{ test:'zinn',        factor:'personal',       range:'balanced',  narrative:'' },

	{ test:'pf16global',  factor:'extraversion',   range:'high',      narrative:'' },
	{ test:'pf16global',  factor:'extraversion',   range:'low',       narrative:'I have a high ability to work in solitary conditions.' },
	{ test:'pf16global',  factor:'extraversion',   range:'balanced',  narrative:'' },
	{ test:'pf16global',  factor:'anxiety',        range:'high',      narrative:'' },
	{ test:'pf16global',  factor:'anxiety',        range:'low',       narrative:'I have an ability to deal with a great deal of anxiety and to heal from it.  I am a survivor.' },
	{ test:'pf16global',  factor:'anxiety',        range:'balanced',  narrative:'' },
	{ test:'pf16global',  factor:'tough',          range:'high',      narrative:'I can be tough-minded and see the value of black and white thinking.' },
	{ test:'pf16global',  factor:'tough',          range:'low',       narrative:'' },
	{ test:'pf16global',  factor:'tough',          range:'balanced',  narrative:'' },
	{ test:'pf16global',  factor:'independence',   range:'high',      narrative:'' },
	{ test:'pf16global',  factor:'independence',   range:'low',       narrative:'' },
	{ test:'pf16global',  factor:'independence',   range:'balanced',  narrative:'' },
	{ test:'pf16global',  factor:'selfcontrol',    range:'high',      narrative:'I am good at curbing my urges.' },
	{ test:'pf16global',  factor:'selfcontrol',    range:'low',       narrative:'' },
	{ test:'pf16global',  factor:'selfcontrol',    range:'balancec',  narrative:'' },

	{ test:'pf16primary', factor:'warm',           range:'high',      narrative:'I have the ability to create what is called an impersonal vibration.  This is the ability to allow people to have their emotions without fixing them.' },
	{ test:'pf16primary', factor:'warm',           range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'warm',           range:'balanced',  narrative:'I have an almost balanced bar on being warm and open to people, versus reserved and impersonal. If used properly, this could become a very valuable tool for me in interacting with people.' },
	{ test:'pf16primary', factor:'abstract',       range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'abstract',       range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'abstract',       range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'stable',         range:'high',      narrative:'I have the ability not to be emotionally involved' },
	{ test:'pf16primary', factor:'stable',         range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'stable',         range:'balanced',  narrative:'I am balanced between Emotional Control and Reactivity and can understand both sides.' },
	{ test:'pf16primary', factor:'dominant',       range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'dominant',       range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'dominant',       range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'lively',         range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'lively',         range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'lively',         range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'rule',           range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'rule',           range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'rule',           range:'balanced',  narrative:'I have a balanced bar between nonconforming and expedient, and rule conscious and dutiful. This shows a balance between conventional and unconventional thinking.' },
	{ test:'pf16primary', factor:'bold',           range:'high',      narrative:'' },  
	{ test:'pf16primary', factor:'bold',           range:'low',       narrative:'' },  
	{ test:'pf16primary', factor:'bold',           range:'balanced',  narrative:'I have the gift of not being too forthright and not telling too much.' },  
	{ test:'pf16primary', factor:'sensitive',      range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'sensitive',      range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'sensitive',      range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'vigilant',       range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'vigilant',       range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'vigilant',       range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'abstracted',     range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'abstracted',     range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'abstracted',     range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'private',        range:'high',      narrative:'I have the gift of not being too forthright and not telling too much.' },
	{ test:'pf16primary', factor:'private',        range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'private',        range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'apprehensive',   range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'apprehensive',   range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'apprehensive',   range:'balanced',  narrative:'' },
	{ test:'pf16primary', factor:'open',           range:'high',      narrative:'I am very open to and able to embrace change, which is the law of the universe.' },
	{ test:'pf16primary', factor:'open',           range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'open',           range:'balanced',  narrative:'I have the gift of balance between traditional and open to change thinking.' },
	{ test:'pf16primary', factor:'selfreliant',    range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'selfreliant',    range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'selfreliant',    range:'balanced',  narrative:'I balanced between group orientation and self-reliance.' },
	{ test:'pf16primary', factor:'perfectionist',  range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'perfectionist',  range:'low',       narrative:'I have a high tolerance for disorder and can come up with creative solutions in the moment.' },
	{ test:'pf16primary', factor:'perfectionist',  range:'balanced',  narrative:'I have a balanced bar between tolerance for disorder and perfection. This indicates I can deal with a balanced amount of both; but if someone is too disorderly or sloppy, or overly compulsive, it will bother me.' },
	{ test:'pf16primary', factor:'tense',          range:'high',      narrative:'' },
	{ test:'pf16primary', factor:'tense',          range:'low',       narrative:'' },
	{ test:'pf16primary', factor:'tense',          range:'balanced',  narrative:'I have a balance between being composed and relaxed, intense and driven.  This means that I function within a balance of both of these, but going too far out either way will bother I.' },

	{ test:'eji',         factor:'problemsolving', range:'high',      narrative:'The ability to use the emotions in problem solving.' },
]
